../rtl/uriscv/core/uriscv_defs.sv
../rtl/uriscv/core/uriscv_alu.sv
../rtl/uriscv/core/uriscv_lsu.sv
../rtl/uriscv/core/uriscv_csr.sv
../rtl/uriscv/core/uriscv_muldiv.sv
../rtl/uriscv/core/uriscv_branch.sv
../rtl/uriscv/core/uriscv_core.sv
../rtl/uriscv/core/uriscv_tcm.sv
../rtl/uriscv/core/uriscv_top.sv
../rtl/uriscv/core/uriscv_ahb_top.sv
../rtl/uriscv/core/uriscv_axi_top.sv
../rtl/ip/axi_infrastructure/arbiter.v
../rtl/ip/axi_infrastructure/priority_encoder.v
../rtl/ip/axi_infrastructure/axi_register_rd.v
../rtl/ip/axi_infrastructure/axi_register_wr.v
../rtl/ip/axi_infrastructure/axi_crossbar_addr.v
../rtl/ip/axi_infrastructure/axi_crossbar_rd.v
../rtl/ip/axi_infrastructure/axi_crossbar_wr.v
../rtl/ip/axi_infrastructure/axi_crossbar.v
../rtl/ip/axi4_ram_bridge.v
../rtl/ip/axilite_slave.v
../rtl/ip/ahb_ram.v
../rtl/ip/ahb_pio.v
../rtl/ip/axi_ram.v
../rtl/ip/ram.v
../rtl/top/top.v
